---
title: "Exce&#231;&#245;es de solu&#231;&#227;o de problemas: System.Reflection.TargetException | Microsoft Docs"
ms.custom: ""
ms.date: "10/29/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "devlang-csharp"
ms.tgt_pltfrm: ""
ms.topic: "article"
helpviewer_keywords: 
  - "Exceção System.Reflection.TargetException"
  - "Exceção TargetException"
ms.assetid: 88b8e4b4-f1a3-4c4a-b1ef-cac176160803
caps.latest.revision: 6
caps.handback.revision: 6
author: "mikeblome"
ms.author: "mblome"
manager: "douge"
---
# Exce&#231;&#245;es de solu&#231;&#227;o de problemas: System.Reflection.TargetException
A exceção que é lançada quando é feita uma tentativa de invocar um destino inválido.  
  
## Comentários  
 A <xref:System.Reflection.TargetException> é lançada quando é feita uma tentativa de chamar um método não estático em um objeto nulo. Isso pode ocorrer porque o chamador não tem acesso ao membro, ou porque o destino não define o membro ou condições semelhantes.  
  
## Consulte também  
 <xref:System.Reflection.TargetException>   
 [Use the Exception Assistant](../Topic/How%20to:%20Use%20the%20Exception%20Assistant.md)