---
title: C28198 | Microsoft Docs
ms.custom: ''
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C28198
helpviewer_keywords:
- C28198
ms.assetid: 8bad4acb-712c-43f5-81d1-45d92092d4c5
caps.latest.revision: 5
author: corob-msft
ms.author: gewarren
manager: ghogen
ms.openlocfilehash: 3d574371401a009b2d5b12708ad347925aca6cc2
ms.sourcegitcommit: 9ceaf69568d61023868ced59108ae4dd46f720ab
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 10/12/2018
ms.locfileid: "49292013"
---
# <a name="c28198"></a>C28198
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Aviso C28198: possível vazamento de memória devido a uma exceção.  
  
 Este aviso indica que a memória alocada não está sendo liberado após uma exceção será gerada. A instrução no final do caminho pode gerar uma exceção. A memória foi passada para uma função que possam ter salvo uma cópia a ser liberada posteriormente.  
  
 Esse aviso é muito semelhante ao aviso [C28197](../code-quality/c28197.md). As anotações que são recomendadas para uso com aviso [C28197](../code-quality/c28197.md) também podem ser usados aqui.  
  
## <a name="example"></a>Exemplo  
 O exemplo de código a seguir gera este aviso:  
  
```  
char *p1 = new char[10];  
char *p2 = new char[10];  
  
test(p1);   // does not save a copy of p  
  
delete[] p2;  
delete[] p1;  
```  
  
 O exemplo de código a seguir evita este aviso:  
  
```  
char *p1 = new char[10];  
char *p2 = NULL;  
  
test(p1);   // does not save a copy of p  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
```



