---
title: "C26111 | Microsoft Docs"
ms.custom: ""
ms.date: "12/03/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "vs-devops-test"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "C26111"
helpviewer_keywords: 
  - "C26111"
ms.assetid: 85fc740a-3bbb-41b8-a848-95e243a08da9
caps.latest.revision: 8
caps.handback.revision: 8
author: "corob-msft"
ms.author: "corob"
manager: "ghogen"
---
# C26111
[!INCLUDE[vs2017banner](../code-quality/includes/vs2017banner.md)]

Aviso C26111: Chamador falhando ao tentar liberar o bloqueio \<lock\> antes de chamar a função \<fun\>.  
  
 A anotação `_Requires_lock_not_held_` impor um pré\-requisito que a contagem de bloqueio do bloqueio especificado não pode ser maior que zero quando a função é chamada.  C26111 de aviso é emitido quando uma função não libera o bloqueio antes que chama outra função.  
  
## Exemplo  
 O exemplo a seguir gerenciar C26111 de aviso porque a pré\-requisito de `_Requires_lock_not_held_` é violada pela chamada a `DoNotLock` na seção bloqueado.  
  
```  
  
typedef struct _DATA   
{  
    CRITICAL_SECTION cs;  
    int d;  
} DATA;  
  
_Requires_lock_not_held_(p->cs)   
  
void DoNotLock(DATA* p)  
{  
    EnterCriticalSection(&p->cs);   
    p->d = 0;  
    LeaveCriticalSection(&p->cs);  
}  
  
void LockedFunction(DATA* p)   
{   
    EnterCriticalSection(&p->cs);   
    DoNotLock(p); // Warning C26111  
    LeaveCriticalSection(&p->cs);  
}  
  
```