---
title: C6103 | Microsoft Docs
ms.custom: 
ms.date: 11/04/2016
ms.reviewer: 
ms.suite: 
ms.technology:
- vs-ide-code-analysis
ms.tgt_pltfrm: 
ms.topic: article
f1_keywords:
- C6103
ms.assetid: 22d1ab35-31a3-4ba9-8ef4-7a64bce66621
caps.latest.revision: 
author: mikeblome
ms.author: mblome
manager: ghogen
ms.workload:
- multiple
ms.openlocfilehash: e3d141d793609409596c72ee69b24af1a3d2f130
ms.sourcegitcommit: 32f1a690fc445f9586d53698fc82c7debd784eeb
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 12/22/2017
---
# <a name="c6103"></a>C6103
Aviso C6103: retornando \<variável > de falha na chamada de função na linha \<local >.  
  
 Um caminho bem-sucedido por meio da função está retornando uma variável usada como um parâmetro `_Out_` para uma chamada de função interna malsucedida.  
  
 O problema talvez seja a função chamada e a função de chamada não anotadas por completo. A função de chamada pode exigir `_Always_`, `_Outptr_result_nullonfailure_` (`_COM_Outptr_` para código COM), ou uma anotação relacionada, e a função de chamada pode exigir uma anotação `_Success_`. Outra causa possível para esse aviso é que a anotação `_Success_` na função chamada está incorreta.  
  
## <a name="see-also"></a>Consulte também  
 [Usando anotações de SAL para reduzir defeitos de código do C/C++](../code-quality/using-sal-annotations-to-reduce-c-cpp-code-defects.md)